spring:
  shardingsphere:
    datasource:
      names:  master,slave0,slave1
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://rm-8vbunk5pgvx23z223.mysql.zhangbei.rds.aliyuncs.com:3306/hello?characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: Szj123456$
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/hello?characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: Xc123456$
    masterslave:
      load-balance-algorithm-type: round_robin
      name: ms
      master-data-source-name: master
      slave-data-source-names: slave0,slave1
    props:
      sql:
        show: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: yestoberich
server:
  port: 6666