sharding:
  jdbc:
    dataSource:
      #    扩展  ,db-test2
      names: db-test0,db-test1
      # 配置主库
      db-test0: #org.apache.tomcat.jdbc.pool.DataSource
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://rm-8vbunk5pgvx23z223.mysql.zhangbei.rds.aliyuncs.com:3306/hello?characterEncoding=utf-8&allowMultiQueries=true
        username: general
        password: General123456$
      db-test1: # 配置第一个从库
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/hello?characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: Xc123456$
    config:
      masterslave: # 配置读写分离
        load-balance-algorithm-type: round_robin # 配置从库选择策略，提供轮询与随机，这里选择用轮询//random 随机 //round_robin 轮询
        name: db1s2
        master-data-source-name: db-test0
        slave-data-source-names: db-test1
    #        ,db-test2
    props:
      sql: # 开启SQL显示，默认值: false，注意：仅配置读写分离时不会打印日志！！！
        show: true

server:
  port: 7777

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: yestoberich

